language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<2.0"
install:
  - pip install PLY
  - pip install -U $DJANGO
  - pip install -e .
script: python test_project/manage.py test core.tests
notifications:
  slack: ivelum:m5sGlwz1uEy5sQ32n0kg9lNh
