# Generated by Django 4.2.30 on 2026-08-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_similar_books_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='binary_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
