name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
        django: [1.8.*, 1.9.*, 1.10.*, 1.11.*, 2.0.*, 2.1.*, 2.2.*, 3.0.*, 3.1.*]
        exclude:
          - python: 2.7
            django: 2.0.*
          - python: 2.7
            django: 2.1.*
          - python: 2.7
            django: 2.2.*
          - python: 2.7
            django: 3.0.*
          - python: 2.7
            django: 3.1.*
          - python: 3.5
            django: 3.0.*
          - python: 3.5
            django: 3.1.*
          - python: 3.7
            django: 1.11.*
          - python: 3.8
            django: 1.9.*
          - python: 3.8
            django: 1.10.*
          - python: 3.9
            django: 1.9.*
          - python: 3.9
            django: 1.10.*
    steps:
      # Send build notifications to Slack
      - uses: voxmedia/github-action-slack-notify-build@v1
        id: slack
        with:
          channel: teamplify
          status: STARTED
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - name: get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: cache pip
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip|${{ matrix.python }}|${{ matrix.django }}
      - run: pip install PLY
      - run: pip install Django==${{ matrix.django }}
      - run: pip install -e .
      - run: python test_project/manage.py test core.tests

      # Send notification on build success
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: teamplify
          status: SUCCESS
          color: good

      # Send notification on build failure
      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: teamplify
          status: FAILED
          color: danger